repository: BYR-Navi/BYR-Navi
repository_url: https://github.com/BYR-Navi/BYR-Navi

timezone: Asia/Shanghai
lang: zh_CN

title: BYR-Navi导航
alias_en: BYR-Navi
alias_cn: BYR-Navi导航
description: A Navigation Website for BYR
keywords:  BYR-Navi, BYR, BUPT, Navi, Navigation
url: https://byr-navi.com
established_at: "2016-10-01T00:00+08:00"

author: iROCKBUNNY
author_url: #
organization: TEELAB
organization_url: #
contact: #

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor